### ISSUE TITLE
Interface Problem within Chrome

### ISSUE THREAD

**Issue by Fulvio0294** [elmot/open-oscilloscope-stm32f3#1]
I have properly mounted the oscilloscope as illustrated, I'm using a waveform generator to produce the input signal. I'm definitely sure the signal generator is functioning properly as I have tested it on an actual oscilloscope. 
When I launch the _oscilloscope interface_ within Chrome the waveform's plot just doesn't show up, all I can see is an empty frame and the settings sidebar. I wonder if further action is needed to properly set and run the corresponding java applet. Any suggestions?

**Comment by elmot** [comment]
At first, let me thank you for the testing of the project.

Some notes, related to project status.
- The project is not finished yet, and it's on hold for the moment, because I'm quite busy with other stuff. 
- There are bugs in the firmware, and the oscilloscope does not work properly.
- This project does not use any java applets, since they are outdated and retired from all the browser platforms. The project is made as a packaged Chrome App, which is based on JavaScript, but not on java applets.
- Recently Google has announced removal of that type of apps, and that means the platform is outdated already and I shall migrate PC software to something else. They announced a new API, WebUSB, which is not released yet. Let's see, what will happen.
- Taking in account latter google's decisions related to their products, I'm not sure if I want to be tied to their products and APIs anymore. And again, let's see, what will happen.

Nevertheless, the project is not going to be abandoned, and I will keep the issue open until it's fixed or rewritten to other tickets.

**Comment by elmot** [comment]
Fixed with new approach
